(function(){
"use strict";
if(window.IMC_CLUBHOUSE)return;
const VERSION="1.4.0";
let state={container:null,client:null,user:null,managerId:"",username:"",worlds:[],assignments:[],teams:new Map(),nations:new Map()};
const clean=v=>String(v==null?"":v).trim();
const esc=v=>clean(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function isActive(a){const d=new Date().toISOString().slice(0,10);return(!a.start_date||a.start_date<=d)&&(!a.end_date||a.end_date>=d)}
function worldName(id){const w=state.worlds.find(x=>x.game_world_id===id);return clean(w&&(w.imc_name||w.name||w.soccer_manager_name))||id}
function teamKey(w,t){return clean(w)+"|"+clean(t)}
function teamName(a){return a.assignment_type==="national_team"?(state.nations.get(String(a.nation_id))||"Nazionale"):(state.teams.get(teamKey(a.game_world_id,a.team_id))||"Club")}
async function load(){const r=await state.client.rpc("imc_nexus_gateway",{p_action:"club_house",p_args:{managerId:state.managerId}});if(r.error)throw r.error;const d=r.data||{};state.worlds=Array.isArray(d.worlds)?d.worlds:[];state.assignments=Array.isArray(d.assignments)?d.assignments:[];state.teams=new Map((d.teams||[]).map(x=>[teamKey(x.game_world_id,x.team_id),clean(x.display_name||x.team_name)]));state.nations=new Map((d.nations||[]).map(x=>[String(x.nation_id),clean(x.nation_name)]))}
function groupActive(){const m=new Map();state.assignments.filter(isActive).forEach(a=>{const id=clean(a.game_world_id);if(!id)return;if(!m.has(id))m.set(id,[]);m.get(id).push(a)});return [...m.entries()].sort((a,b)=>a[0].localeCompare(b[0]))}
function pulseCard([id,items]){const roles=items.map(a=>`<div class="ch-role"><strong>${esc(teamName(a))}</strong><em>${a.assignment_type==="national_team"?"NAZIONALE":"CLUB"}</em></div>`).join("");return `<button class="ch-pulse" data-ch-world="${esc(id)}"><span>${esc(id)}</span><small>${esc(worldName(id))}</small><div class="ch-role-list">${roles}</div></button>`}
function menuWorlds(){return state.worlds.filter(w=>/^GW00[1-9]$/.test(clean(w.game_world_id))).sort((a,b)=>clean(a.game_world_id).localeCompare(clean(b.game_world_id))).map(w=>`<button type="button" data-ch-world="${esc(w.game_world_id)}"><span>${esc(w.game_world_id)}</span><strong>${esc(worldName(w.game_world_id))}</strong></button>`).join("")}
function render(){const root=state.container;if(!root)return;const grouped=groupActive();root.innerHTML=`<section class="clubhouse" data-clubhouse-version="${VERSION}"><div class="ch-header-shell"><header class="ch-top"><div class="ch-brand-panel"><img src="assets/imc-logo.png" alt="IMC"></div><div class="ch-brand-title"><h1>NEXUS</h1><small><i></i>CLUB HOUSE<i></i></small></div><button class="ch-menu" type="button" data-ch-menu aria-label="Apri menu" aria-expanded="false"><i></i><i></i><i></i></button></header><div class="ch-drawer" data-ch-drawer hidden><div class="ch-drawer-head"><strong>GAME WORLD</strong><button type="button" data-ch-menu-close aria-label="Chiudi menu">×</button></div><div class="ch-drawer-worlds">${menuWorlds()}</div></div></div><section class="ch-section"><div class="ch-title"><h2>WORLD PULSE</h2><span>${grouped.length} GAME WORLD</span></div><div class="ch-pulses">${grouped.length?grouped.map(pulseCard).join(""):'<div class="ch-empty">Nessun incarico attivo.</div>'}</div></section><section class="ch-section"><div class="ch-title"><h2>NEXUS FEED</h2><span>LIVE</span></div><div class="ch-feed"><article><b class="green">RESULT</b><small>AGGIORNAMENTI DA TUTTI I GAME WORLD</small><strong>I risultati recenti appariranno qui.</strong></article><article><b class="blue">TRANSFER</b><small>GLOBAL TRANSFER MARKET</small><strong>I nuovi trasferimenti appariranno qui.</strong></article><article><b class="gold">TROPHY</b><small>TROPHY ROOM</small><strong>I nuovi trofei appariranno qui.</strong></article><article><b class="violet">MANAGER</b><small>MANAGER NETWORK</small><strong>I cambi di incarico appariranno qui.</strong></article></div></section><section class="ch-section"><div class="ch-title"><h2>GLOBAL SCHEDULE</h2><span>PROSSIME</span></div><div class="ch-tabs"><button class="active">OGGI</button><button>DOMANI</button><button>SETTIMANA</button></div><div class="ch-schedule"><div class="ch-empty">Le prossime partite di club e nazionali saranno aggregate qui dai Game World.</div></div></section></section>`}
async function mount(o){if(!o||!o.container||!o.client||!o.managerId)throw Error("Club House: parametri mancanti");state={...state,...o,managerId:clean(o.managerId),username:clean(o.username)};state.container.innerHTML='<div class="ch-loading">Caricamento Club House…</div>';await load();render()}
function unmount(){if(state.container)state.container.innerHTML="";state.container=null}
document.addEventListener("click",e=>{const world=e.target.closest&&e.target.closest("[data-ch-world]");if(world){document.dispatchEvent(new CustomEvent("nexus:navigate",{detail:{target:"game-world",worldId:clean(world.getAttribute("data-ch-world"))}}));return}const open=e.target.closest&&e.target.closest("[data-ch-menu]");if(open){const drawer=state.container&&state.container.querySelector("[data-ch-drawer]");if(drawer){const willOpen=drawer.hidden;drawer.hidden=!willOpen;open.setAttribute("aria-expanded",String(willOpen))}return}const close=e.target.closest&&e.target.closest("[data-ch-menu-close]");if(close){const drawer=state.container&&state.container.querySelector("[data-ch-drawer]");const btn=state.container&&state.container.querySelector("[data-ch-menu]");if(drawer)drawer.hidden=true;if(btn)btn.setAttribute("aria-expanded","false")}});
window.IMC_CLUBHOUSE={version:VERSION,mount,unmount};
})();