(function(){
"use strict";
if(window.IMC_COMPETITIONS)return;
const VERSION="2.0.0";
let state={container:null,client:null,worldId:"",worldName:"",items:[],seasons:[]};
function clean(v){return String(v==null?"":v).trim()}
function esc(v){return clean(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function typeOf(x){return clean(x&&x.IMC_competition_type).toLowerCase()}
function actionOf(x){return clean(x&&x.sm_action).toLowerCase()}
function countType(v){return state.items.filter(x=>typeOf(x)===v).length}
function countAction(v){return state.items.filter(x=>actionOf(x)===v).length}
function countryCount(){return new Set(state.items.filter(x=>typeOf(x)==="domestic").map(x=>clean(x["Country Nexus View"]||x.sm_country)).filter(Boolean)).size}
function formatDate(v){const s=clean(v);if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return "—";const [y,m,d]=s.split("-").map(Number),months=["GEN","FEB","MAR","APR","MAG","GIU","LUG","AGO","SET","OTT","NOV","DIC"];return `${String(d).padStart(2,"0")} ${months[m-1]||""} ${y}`}
function trophyIcon(){return `<svg viewBox="0 0 120 120" aria-hidden="true"><defs><linearGradient id="cpCup" x1="0" x2="1"><stop offset="0" stop-color="#d8e0ea"/><stop offset=".45" stop-color="#fff"/><stop offset=".7" stop-color="#9aaabc"/><stop offset="1" stop-color="#f8fbff"/></linearGradient><linearGradient id="cpGold" x1="0" x2="1"><stop offset="0" stop-color="#c99a35"/><stop offset=".5" stop-color="#f2d47a"/><stop offset="1" stop-color="#b98320"/></linearGradient></defs><path d="M35 18h50v23c0 25-10 40-25 48-15-8-25-23-25-48Z" fill="url(#cpCup)" stroke="#7e8da0" stroke-width="2"/><path d="M35 27H22c0 24 7 34 24 36M85 27h13c0 24-7 34-24 36" fill="none" stroke="url(#cpGold)" stroke-width="5" stroke-linecap="round"/><path d="M55 88h10v11h16v8H39v-8h16Z" fill="url(#cpCup)" stroke="#8b99aa" stroke-width="1.5"/></svg>`}
function globeIcon(){return `<svg viewBox="0 0 120 120" aria-hidden="true"><defs><radialGradient id="cpGlobe" cx="35%" cy="30%"><stop offset="0" stop-color="#5aa2ff"/><stop offset=".5" stop-color="#0d4d9b"/><stop offset="1" stop-color="#082b63"/></radialGradient></defs><circle cx="60" cy="60" r="39" fill="url(#cpGlobe)" stroke="#d7ad48" stroke-width="2"/><path d="M22 60h76M60 21c14 15 20 27 20 39S74 84 60 99M60 21C46 36 40 48 40 60s6 24 20 39M32 38c17 9 39 9 56 0M32 82c17-9 39-9 56 0" fill="none" stroke="#dbe9fb" stroke-width="2" opacity=".9"/></svg>`}
function flagIcon(){return `<svg viewBox="0 0 120 120" aria-hidden="true"><defs><linearGradient id="cpFlag" x1="0" x2="1"><stop offset="0" stop-color="#f6f8fb"/><stop offset=".55" stop-color="#fff"/><stop offset="1" stop-color="#dbe3ee"/></linearGradient></defs><path d="M29 15v91" stroke="#a97722" stroke-width="4"/><path d="M33 21c20-12 37 8 58-2v45c-21 10-38-10-58 2Z" fill="url(#cpFlag)" stroke="#9ba9b9" stroke-width="2"/><circle cx="62" cy="43" r="12" fill="#0d4d9b" opacity=".92"/><path d="M55 43h14M62 36v14" stroke="#d7ad48" stroke-width="2"/></svg>`}
function statIcon(type){const map={countries:'<circle cx="12" cy="12" r="8"/><path d="M4 12h16M12 4c3 3 4 5 4 8s-1 5-4 8M12 4c-3 3-4 5-4 8s1 5 4 8"/>',leagues:'<path d="M5 5h14v4c0 5-3 8-7 10-4-2-7-5-7-10Z"/><path d="M8 5V3h8v2"/>',cup:'<path d="M7 4h10v4c0 5-2 8-5 9-3-1-5-4-5-9V4Z"/><path d="M9 17v3h6v-3M4 6H2c0 4 2 6 5 6M20 6h2c0 4-2 6-5 6"/>',shield:'<path d="M12 3 20 6v6c0 5-3 8-8 10-5-2-8-5-8-10V6Z"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true">${map[type]||""}</svg>`}
async function load(){const [c,s]=await Promise.all([state.client.rpc("imc_nexus_gateway",{p_action:"gw_competitions",p_args:{gameWorld:state.worldId}}),state.client.rpc("imc_nexus_gateway",{p_action:"imc_seasons",p_args:{gameWorld:state.worldId}})]);if(c.error)throw c.error;if(s.error)throw s.error;state.items=(c.data&&c.data.rows)||[];state.seasons=(s.data&&s.data.rows)||[]}
function render(){if(!state.container)return;const domestic=countType("domestic"),international=countType("international"),nations=countType("nations"),countries=countryCount(),leagues=countAction("league"),nationalCups=countAction("leaguecup"),leagueCups=countAction("leagueshield"),charity=countAction("charityshield"),season=state.seasons[0]||{},seasonLabel=clean(season.imc_season||season.soccer_manager_season||"—"),start=formatDate(season.imc_season_start_date),end=formatDate(season.imc_season_end_date);state.container.innerHTML=`<section class="cp-hub" data-competitions-version="${VERSION}"><section class="cp-world-strip"><div class="cp-world-mark"><span>${esc(state.worldId)}</span><strong>${esc(state.worldName||state.worldId)}</strong></div><div class="cp-world-season"><b>SEASON ${esc(seasonLabel)}</b><small>${start} — ${end}</small></div></section><div class="cp-hub-title"><span>COMPETITIONS HUB</span></div><section class="cp-domestic"><div class="cp-domestic-copy"><span class="cp-kicker">DOMESTIC</span><div class="cp-count"><strong>${domestic}</strong><b>COMPETITIONS</b></div><div class="cp-ecosystem"><div>${statIcon("countries")}<strong>${countries}</strong><span>COUNTRIES</span></div><div>${statIcon("leagues")}<strong>${leagues}</strong><span>LEAGUES</span></div><div>${statIcon("cup")}<strong>${nationalCups}</strong><span>NATIONAL<br>CUPS</span></div><div>${statIcon("cup")}<strong>${leagueCups}</strong><span>LEAGUE<br>CUPS</span></div><div>${statIcon("shield")}<strong>${charity}</strong><span>CHARITY<br>SHIELDS</span></div></div></div><div class="cp-domestic-art">${trophyIcon()}</div></section><section class="cp-secondary-grid"><article class="cp-secondary cp-international"><div><span>INTERNATIONAL</span><strong>${international}</strong><small>COMPETITIONS</small></div><div class="cp-secondary-art">${globeIcon()}</div></article><article class="cp-secondary cp-nations"><div><span>NATIONS</span><strong>${nations}</strong><small>COMPETITIONS</small></div><div class="cp-secondary-art">${flagIcon()}</div></article></section></section>`}
async function mount(opts){if(!opts||!opts.container||!opts.client||!opts.worldId)throw new Error("Competitions: parametri mancanti");state={...state,...opts,worldId:clean(opts.worldId),worldName:clean(opts.worldName),items:[],seasons:[]};state.container.innerHTML='<div class="cp-loading">Caricamento Competition Hub…</div>';await load();render()}
function unmount(){if(state.container)state.container.innerHTML="";state.container=null}
window.IMC_COMPETITIONS={version:VERSION,mount,unmount};
})();